### ISSUE TITLE
Text rendering has half and quarter pixels

### ISSUE THREAD

**Issue by NoahTheNerd** [Polyfrost/VanillaHUD#19]
No way to disable this goofy text renderer either from the looks of it.

![image](https://github.com/user-attachments/assets/b847b2a0-8955-4376-b638-0e4b43c3b5b6)

**Comment by Wyvest** [comment]
This isn't our issue... we don't change the font renderer in any way

Turn off patcher font renderer and see if it fixes. If it doesn't, feel free to make a ticket at polyfrost.org/discord
